# Install kubeadm kubelet kubectl

- name: Install apt-transport-https ca-certificates
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl

- name: Use the k8s apt key
  get_url:
    url: https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/Release.key
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
    mode: "0644"

- name: Отобразить результат добавления GPG ключа Kubernetes
  ansible.builtin.debug:
    var: add_k8s_gpg_key_result

- name: Install k8s apt sources
  apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/ /
    state: present

- name: Install kubelet kubeadm kubectl
  ansible.builtin.apt:
    pkg:
      - kubelet
      - kubeadm
      - kubectl

- name: Hold kubelet
  dpkg_selections:
    name: kubelet
    selection: hold

- name: Hold kubeadm
  dpkg_selections:
    name: kubeadm
    selection: hold

- name: Hold kubectl
  dpkg_selections:
    name: kubectl
    selection: hold

- name: Install bash-completion package (if not already installed)
  become: yes
  package:
    name: bash-completion
    state: present

- name: Enable kubectl auto-completion for the current user
  become: yes
  become_user: "{{ kube_user }}"
  shell: |
    echo "source <(kubectl completion bash)" >> ~/.bashrc
    source ~/.bashrc
  args:
    executable: /bin/bash

- name: Ensure kubectl auto-completion is enabled system-wide
  become: yes
  lineinfile:
    path: /etc/bash_completion.d/kubectl
    create: yes
    line: "source <(kubectl completion bash)"

- name: Reload shell configuration for the current session
  become: yes
  shell: |
    source ~/.bashrc
  args:
    executable: /bin/bash