- name: Ensure Python3 is installed
  ansible.builtin.package:
    name: python3
    state: present

- name: Ensure pip3 is installed
  ansible.builtin.package:
    name: python3-pip
    state: present
