
kube_user: habib
kube_home: /home/habib
file_path: "/boot/firmware/cmdline.txt"
kubernetes_config_path: "/etc/kubernetes/admin.conf"
kubernetes_join_path: "/home/habib/kubeadm_init_output.log"
kubernetes_version: "v1.32"
flannel_version: "v0.26.2"
metallb_version: v0.14.8
master_1_ip: "192.168.1.30"
cidr_pods: "10.244.0.0/16"
cidr_metal: "192.168.1.50-192.168.1.90"
token: "0qncmm.a1bssl1kkffrlxq4"
discovery_token: "e6c708e70faf30d780fe21efc1c6c82cfaa250ea2dd3e4d0af415db0fe39d6bf"
certificate_key: "d3f3a6bdce198b424f7161fa049c96c7c222acdf85be68e58053ff46024d1b63"
namespace_name_1: prod
namespace_name_2: stage
namespace_name_3: test
