---
- name: Playbook to install kubernetes node
  hosts: setup_k8s_masters_additionals
  become: yes
  gather_facts: no
  vars_files:
    - ../group_vars/setup-k8s-general.yml
  roles:
    - role: ../roles/setup-k8s-masters-additionals

