- name: Copy namespace manifest to target
  template:
    src: nfs-storage.yml
    dest: /tmp/nfs-storage.yml
    owner: "{{ kube_user }}"
    group: "{{ kube_user }}"
    mode: '0644'

- name: Apply NFS storage config manifest
  become: yes
  become_user: "{{ kube_user }}"
  shell: |
    kubectl apply -f /tmp/nfs-storage.yml
  environment:
    KUBECONFIG: "{{ kube_home }}/.kube/config"