- name: Copy namespace manifest to target
  template:
    src: namespaces.yml.j2
    dest: /tmp/namespaces.yml
    owner: "{{ kube_user }}"
    group: "{{ kube_user }}"
    mode: '0644'

- name: Create a Neamespaces
  kubernetes.core.k8s:
    state: present
    src: /tmp/namespaces.yml
    kubeconfig: /home/habib/.kube/config
