- name: Copy namespace manifest to target
  template:
    src: namespaces.yml.j2
    dest: /tmp/namespaces.yml
    owner: "{{ kube_user }}"
    group: "{{ kube_user }}"
    mode: '0644'

- name: Apply Neamespaces manifest
  become: yes
  become_user: "{{ kube_user }}"
  shell: |
    kubectl apply -f /tmp/namespaces.yml
  environment:
    KUBECONFIG: "{{ kube_home }}/.kube/config"