- name: Debug variables
  debug:
    msg:
      - "Master IP: {{ master_1_ip }}"
      - "Token: {{ token }}"
      - "Discovery Token: {{ discovery_token }}"
      
- name: Execute kubeadm join command
  shell: |
    kubeadm join {{ master_1_ip }}:6443 --token {{ token }} \
    --discovery-token-ca-cert-hash sha256:{{ discovery_token }} --control-plane --certificate-key {{ certificate_key }}
  args:
    executable: /bin/bash